# Documentation
The database consists of multiple tables with multiple columns. For each table and column, in the database there is a comment stored, explaining in more detail the meaning and use of it.

### I have a column name what does it mean?

In [3]:
import evaluation.utils.db as db

col_name = 'E_WE__VvsRHE'

doc_table = db.query_sql(''' SELECT * FROM documentation_columns WHERE name_column = %s''',
                         params=[col_name],
                         index_col=['name_column', 'name_table']
                        )
display(doc_table.style.set_properties(**{
    'text-align': 'left',
    'white-space': 'pre-wrap',
}))

### The value of the column is calculated by a view. What is the definition of the View?
Simple calculations are performed by SQL database upon request. The definition of these caluclated columns can be found in the create view statement.

In [15]:
import evaluation.utils.db as db
import sqlparse

name_view = 'data_ec_analysis'

sql_create_view = db.get_create_view(name_view)
print(sqlparse.format(sql_create_view, reindent=True, keyword_case='upper'))

CREATE ALGORITHM=UNDEFINED DEFINER=`nico`@`%` SQL SECURITY DEFINER VIEW `data_ec_analysis` AS
SELECT `d`.`id_exp_sfc` AS `id_exp_sfc`,
       `d`.`id_data_ec` AS `id_data_ec`,
       `d`.`t__s` AS `t__s`,
       if((`d`.`Timestamp` IS NULL),(`e`.`t_start__timestamp` + interval `d`.`t__s` SECOND),`d`.`Timestamp`) AS `Timestamp`,
       `d`.`E_WE_raw__VvsRE` AS `E_WE_raw__VvsRE`,
       `d`.`Delta_E_WE_uncomp__V` AS `Delta_E_WE_uncomp__V`,
       `d`.`E_Signal__VvsRE` AS `E_Signal__VvsRE`,
       `d`.`I__A` AS `I__A`,
       `d`.`overload` AS `overload`,
       `d`.`cycle` AS `cycle`,
       if(((`e`.`ec_R_u__ohm` * `e`.`ec_iR_corr_in_situ__percent`) <> 0),((`d`.`E_WE_raw__VvsRE` + `e`.`ec_E_RE__VvsRHE`) - ((`d`.`I__A` * `e`.`ec_R_u__ohm`) * (1 - (`e`.`ec_iR_corr_in_situ__percent` / 100)))),NULL) AS `E_WE__VvsRHE`,
       ((`d`.`E_WE_raw__VvsRE` + `e`.`ec_E_RE__VvsRHE`) + `d`.`Delta_E_WE_uncomp__V`) AS `E_WE_uncompensated__VvsRHE`,
       (`d`.`E_WE_raw__VvsRE` + `e`.`ec_E_RE__VvsRHE`) AS `E_WE_raw__VvsRHE`,
       ((`d`.`I__A` * 1000) / (`e`.`spots_spot_size__mm2` / 100)) AS `j__mA_cm2geo_spot_size`,
       ((`d`.`I__A` * 1000) / (`e`.`fc_top_name_flow_cell_A_opening_ideal__mm2` / 100)) AS `j__mA_cm2geo_fc_top_cell_Aideal`,
       ((`d`.`I__A` * 1000) / (`e`.`fc_top_name_flow_cell_A_opening_real__mm2` / 100)) AS `j__mA_cm2geo_fc_top_cell_Areal`,
       ((`d`.`I__A` * 1000) / (`e`.`fc_top_id_sealing_A_opening__mm2` / 100)) AS `j__mA_cm2geo_fc_top_sealing`,
       ((`d`.`I__A` * 1000) / (`e`.`fc_top_id_PTL_A_PTL__mm2` / 100)) AS `j__mA_cm2geo_fc_top_PTL`,
       ((`d`.`I__A` * 1000) / (`e`.`fc_bottom_name_flow_cell_A_opening_ideal__mm2` / 100)) AS `j__mA_cm2geo_fc_bottom_cell_Aideal`,
       ((`d`.`I__A` * 1000) / (`e`.`fc_bottom_name_flow_cell_A_opening_real__mm2` / 100)) AS `j__mA_cm2geo_fc_bottom_cell_Areal`,
       ((`d`.`I__A` * 1000) / (`e`.`fc_bottom_id_sealing_A_opening__mm2` / 100)) AS `j__mA_cm2geo_fc_bottom_sealing`,
       ((`d`.`I__A` * 1000) / (`e`.`fc_bottom_id_PTL_A_PTL__mm2` / 100)) AS `j__mA_cm2geo_fc_bottom_PTL`
FROM (`data_ec` `d`
      JOIN `exp_ec_expanded` `e`)
WHERE (`d`.`id_exp_sfc` = `e`.`id_exp_sfc`)

### I want to read documentation of all tables and columns

In [40]:
import evaluation.utils.db as db
from IPython.display import display, Markdown
doc_table = db.query_sql(''' SELECT * FROM documentation_tables''',
                         index_col=['name_table']
                        )
for name_table, row in doc_table.iterrows():
    doc_cols = db.query_sql(''' SELECT name_column, name_inserter, comment, name_axislabel__latex, data_type FROM documentation_columns WHERE name_table = %s''',
                            params=[name_table],
                         index_col=['name_column']
                        )
    display(Markdown(
    f"""### {name_table}
        Table type: {row.table_type}
        Comment: {row.comment_table}
    """))
    #display(doc_cols)
    display(doc_cols.style.set_properties(**{
    'text-align': 'left',
    'white-space': 'pre-wrap',
}))

### ana_icpms_sfc_fitting
        BASE TABLE
        Stores results from sfc icpms fits as performed by Fit_SFC_ICP_MS_Dissolution.py

### ana_icpms_sfc_fitting_peaks
        BASE TABLE
        Stores details of peaks for fits in exp_icpms_sfc_peaks

### ana_integrations
        BASE TABLE
        stores all integration data

### counter_electrodes
        BASE TABLE
        Inventory list of avaiable counter electrode types. Different CEs of the same type are treated as one entry.

### data_compression
        BASE TABLE
        Contains compression data measured in compression experiments

### data_ec
        BASE TABLE
        Data table of all electrochemal direct current experiments identified by id_exp_ec

### data_ec_analysis
        VIEW
        VIEW

### data_ec_polcurve
        BASE TABLE
        averaged data of polarization curve experiments

### data_ec_polcurve_analysis
        VIEW
        VIEW

### data_eis
        BASE TABLE
        Data table of all electrochemical impedance spectroscopy experiments identified by id_exp_ec

### data_eis_analysis
        VIEW
        VIEW

### data_icpms
        BASE TABLE
        Data for all icp_ms experiments. Table stores one analyte-internal standard relationship per time step. If multiple analyte-internalstandard relations are measured they will produce multiple rows.

### data_icpms_internalstandard_fitting
        BASE TABLE
        Data for all icp_ms experiments. Table stores one analyte-internal standard relationship per time step. If multiple analyte-internalstandard relations are measured they will produce multiple rows.

### data_icpms_sfc_analysis
        VIEW
        VIEW

### data_icpms_sfc_analysis_no_ISTD_fitting
        VIEW
        VIEW

### data_icpms_sfc_analysis_old
        VIEW
        VIEW

### data_icpms_sfc_batch_analysis
        VIEW
        VIEW

### data_stability_analysis
        VIEW
        VIEW

### data_stability_batch_analysis
        VIEW
        VIEW

### documentation_columns
        VIEW
        VIEW

### documentation_tables
        VIEW
        VIEW

### dummy_data_icpms_sfc_batch_analysis
        BASE TABLE
        required for view data_icpms_sfc_batch_analysis

### ec_reactions
        BASE TABLE
        holding informations for electrochemical reactions

### electrolytes
        BASE TABLE
        Inventory list of available electrolyte salts

### elements
        BASE TABLE
        holding information of elements of periodic table

### exp_compression
        BASE TABLE
        parameter of compression experiments performed with sfc table

### exp_ec
        BASE TABLE
        parameter of electrochemical experiments. For parameters which can hold more than one value per experiment (for instance multiple gas flows in one experiment) are located in other tables connected to the exp_ec table via the id_exp_ec. Same holds true for different ec techniques such as CV, PEIS , GEIS,... with technique specific parameters. All parameters combined in one table can be found in the corresponding view "exp_ec_expanded". It is recommended to use this one for selecting data to circumvent multiple join statements in the select query.

### exp_ec_cv
        BASE TABLE
        technique specific parameters for cyclic voltammetry (CV)

### exp_ec_datasets
        BASE TABLE
        table of all ec datasets

### exp_ec_datasets_definer
        BASE TABLE
        one ec dataset can consist of multiple exp_ec. This table is defining the n-n relationship

### exp_ec_expanded
        VIEW
        VIEW

### exp_ec_expanded_old
        VIEW
        VIEW

### exp_ec_geis
        BASE TABLE
        technique specific parameters for galvanostatic electrochemical impedance spectroscopy (GEIS)

### exp_ec_ghold
        BASE TABLE
        technique specific parameters for galvanostatic hold (GHOLD), also called one step chronopotentiometry

### exp_ec_gpulse
        BASE TABLE
        technique specific parameters for galvanostatic Pulse technique

### exp_ec_integration
        BASE TABLE
        all information from integration of ec data integration

### exp_ec_integration_expanded
        VIEW
        VIEW

### exp_ec_peis
        BASE TABLE
        technique specific parameters for potentiostatic electrochemical impedance spectroscopy (PEIS)

### exp_ec_phold
        BASE TABLE
        technique specific parameters for galvanostatic hold (PHOLD), also called one step chronoamperometry

### exp_ec_polcurve
        BASE TABLE
        experimental information for polarization curve experiments. (Combination of geis and ghold)

### exp_ec_polcurve_expanded
        VIEW
        VIEW

### exp_ec_ppulse
        BASE TABLE
        technique specific parameters for potentiostatic Pulse technique

### exp_ec_ramp
        BASE TABLE
        technique specific parameters for a potential ramp or linear sweep voltammetry (LSV)

### exp_ec_techniques
        BASE TABLE
        Stores implemented ec techniques, necessary to guarantee a correct storage of technique specific parameters. This is a so-called super/subtype construct.

### exp_icpms
        BASE TABLE
        Table storing all ICPMS experiments including calibration, bulk and sfc-icpms experiments

### exp_icpms_analyte_internalstandard
        BASE TABLE
        Relationship of analyte and internal standard in icp-ms experiment. Multiple relationships can be handled, also multiple analytes for one internal standard and vice versa.

### exp_icpms_batch_expanded
        VIEW
        VIEW

### exp_icpms_calibration_params
        BASE TABLE
        Stores parameter for each analyte internal standard pair in a calibration set as defined in table exp_icpms_analyte_internalstandard.

### exp_icpms_calibration_set
        BASE TABLE

### exp_icpms_integration
        BASE TABLE
        all information from integration of icpmds data integration

### exp_icpms_integration_expanded
        VIEW
        VIEW

### exp_icpms_sfc
        BASE TABLE
        Parameters specific for sfc-icp-ms experiments

### exp_icpms_sfc_batch
        BASE TABLE
        storing experimental parameters for sfc batch experiments

### exp_icpms_sfc_batch_expanded
        VIEW
        VIEW

### exp_icpms_sfc_expanded
        VIEW
        VIEW

### exp_sfc
        BASE TABLE
        parameter of an scanning flow cell experiment. For parameters which can hold more than one value per experiment (for instance multiple gas flows in one experiment) are located in other tables connected to the exp_sfc table via the id_exp_sfc. Same holds true for specific ec parameters (exp_ec) and different ec techniques such as CV, PEIS , GEIS,... with technique specific parameters. All parameters of electrochemical sfc exxperiments can be found combined in one table in the corresponding view "exp_ec_expanded". It is recommended to use this one for selecting data to circumvent multiple join statements in the select query.

### flow_cell_assemblies
        BASE TABLE
        holds information on flow cells and additional parts used in the SFC experiment separated into parts above and below the sample. Above the sample (location = top) which is the commonly used SFC method with a flow cell from the top.  Below the sample (location=bottom) especially introduced for the GDE-SFC to support flow of electrolyte or gas from the back of the sample.

### flow_cells
        BASE TABLE
        Inventory of flow cells capable to supply gas or electrolyte flow to the sample from top (connected to force sensor) or bottom (connected to stage). Can but does not have to have connections for electrodes.

### flow_electrolyte
        BASE TABLE
        parameters of the electrolyte flow(s) within an SFC experiment. Multiple entries for experiments with multiple electrolyte flows (for PTL-SFC)

### flow_gas
        BASE TABLE
        parameters of the gas flow(s) within an SFC experiment. Multiple entries for experiments with multiple gas flows

### gamry_set_ca_speed
        BASE TABLE
        Relation between CA speed name and corresponding index

### gamry_set_control_mode
        BASE TABLE
        Relation between control mode name and corresponding index

### gamry_set_ich_filter
        BASE TABLE
        Relation between ich filter name, corresponding index number and frequency value

### gamry_set_ich_range
        BASE TABLE
        Relation between ich range name, corresponding index number and maximum acceptable voltage between working and counter electrode

### gamry_set_ie_range
        BASE TABLE
        Relation between ie ch range name, corresponding index number and maximum acceptable current between working and counter electrode

### gamry_set_ie_stability
        BASE TABLE
        Relation between ie stability name and corresponding index number

### gamry_set_sampling_mode
        BASE TABLE
        Relation between sampling mode name and corresponding index number

### gamry_set_vch_filter
        BASE TABLE
        Relation between vch filter name, corresponding index number and frequency value

### gamry_set_vch_range
        BASE TABLE
        Relation between ich range name, corresponding index number and maximum acceptable voltage between working and counter electrode (?)

### gases
        BASE TABLE
        Inventory list of available gases

### is_exp_ec_cv
        BASE TABLE
        Recquired for so-called super/subtype construct.

### is_exp_ec_geis
        BASE TABLE
        Recquired for so-called super/subtype construct.

### is_exp_ec_ghold
        BASE TABLE
        Recquired for so-called super/subtype construct.

### is_exp_ec_gpulse
        BASE TABLE
        Recquired for so-called super/subtype construct.

### is_exp_ec_peis
        BASE TABLE
        Recquired for so-called super/subtype construct.

### is_exp_ec_phold
        BASE TABLE
        Recquired for so-called super/subtype construct.

### is_exp_ec_ppulse
        BASE TABLE
        Recquired for so-called super/subtype construct.

### is_exp_ec_ramp
        BASE TABLE
        Recquired for so-called super/subtype construct.

### isotopes
        BASE TABLE
        isotopes used in icpms experiments

### match_exp_sfc_exp_icpms
        VIEW
        VIEW

### match_exp_sfc_exp_icpms
        VIEW
        VIEW

### peristaltic_pumps
        BASE TABLE
        Inventory list of available pump types. Different pumps of the same type are treated as one entry.

### peristaltic_tubings
        BASE TABLE
        Inventory list of tubings used. Each tubing gets a new entry with an unique name, by that aging of the tubings can be tracked.

### porous_transport_layers
        BASE TABLE
        Inventory list of porous transport layers ready to place in the SFC assembly

### publication_exps
        BASE TABLE
        stores entries for all experiments connected to a publication. Creation of table allows for putting all different experiments into the same table no matter on the number of index column. To ensure which multiindex values belong to each other, they must have the same count_exp.

### publications
        BASE TABLE
        stores informations of publications using data in the database

### reference_electrodes
        BASE TABLE
        Inventory list of reference electrodes

### samples
        BASE TABLE
        List of all samples manufactured for and/or used in SFC experiments

### samples_composition
        BASE TABLE
        composition  of a sample is defined in weight percentage of the different materials/elements assuming the whole sample has the same composition. If not specifiy in spots_composition.

### sealings
        BASE TABLE
        Inventory list of all sealings cutted and used for SFC experiments

### setups_icpms
        BASE TABLE
        Inventory list of all inductively coupled plasma mass spectrometry (ICP-MS) setups

### setups_sfc
        BASE TABLE
        Inventory list of all scanning flow cell setups

### spots
        BASE TABLE
        Inventory list of all spots an samples for SFC measurements. coordinates relative to origin in upper left corner

### spots_auto
        VIEW
        VIEW

### spots_composition
        BASE TABLE
        composition  of a spot on a sample is defined in weight percentage of the different materials/elements

### users
        BASE TABLE
        Inventory list of user of this database. Used to define the user of an experiment or owner of a sample.